<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1560477434710" stop="1560477434801">
  <name>scripts</name>
  <labels/>
  <test-cases>
    <test-case start="1560477434710" status="failed" stop="1560477434801">
      <name>C:\Users\苑瑞\Desktop\lianxi\test_day5\scripts.test_.Testlogin.test_hello_001</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;scripts.test_.Testlogin object at 0x0000027D97886E48&gt;

    def test_hello_001(self):
&gt;       assert 0
E       assert 0

scripts\test_.py:3: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="9184-MainThread"/>
        <label name="host" value="DESKTOP-FRP4UEH"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1560477434801" status="passed" stop="1560477434801">
      <name>C:\Users\苑瑞\Desktop\lianxi\test_day5\scripts.test_.Testlogin.test_hello_002</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="9184-MainThread"/>
        <label name="host" value="DESKTOP-FRP4UEH"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1560477434801" status="passed" stop="1560477434801">
      <name>C:\Users\苑瑞\Desktop\lianxi\test_day5\scripts.test_.Testlogin.test_hello_003</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="9184-MainThread"/>
        <label name="host" value="DESKTOP-FRP4UEH"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
